# --- !Ups

CREATE TABLE API_DEFINITIONS (
    KEY varchar(255) NOT NULL PRIMARY KEY,
    BACKLOG_DOMAIN varchar(255) NOT NULL,
    BACKLOG_API_KEY varchar(255) NOT NULL
);

# --- !Downs

DROP TABLE API_DEFINITIONS;
